{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "5589597a_a983e1ce",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 10558
      },
      "writtenOn": "2021-01-12T22:31:26Z",
      "side": 1,
      "message": "In retrospect, the original commit initially failed via \"internal_compile_lite\" but later succeeded in the subsequent attempt which gave false impression that there was no issue with downstream project. \n\nNot sure how it could emit the false positive as it should have stalled with first failure.",
      "revId": "5e79f9c0a3bf78b9c043317586583451ce16aadb",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "accef65f_c7a5a283",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 5634
      },
      "writtenOn": "2021-01-12T22:55:01Z",
      "side": 1,
      "message": "happy to +1 and get out of the way.\n",
      "revId": "5e79f9c0a3bf78b9c043317586583451ce16aadb",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    }
  ]
}