{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "38f8ee50_a13efb3c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 5613
      },
      "writtenOn": "2022-09-27T11:49:41Z",
      "side": 1,
      "message": "thanks and PTAL\nps. the internal_compile_error turned out to be an unrelated bug\nthat mirko is fixing as we speak.",
      "revId": "9a745003e8b6a431663570638ae92d51dd4cc01b",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    }
  ]
}