{
  "comments": [
    {
      "key": {
        "uuid": "cfcd879c_6c48870c",
        "filename": "video/video_send_stream_tests.cc",
        "patchSetId": 2
      },
      "lineNbr": 1894,
      "author": {
        "id": 7332
      },
      "writtenOn": "2019-08-23T03:27:21Z",
      "side": 1,
      "message": "Potential segfault here (heap-use-after-free).\nFor some reason, this task can be called **after** the DestroyCalls() task, both invoked from the thread \u0027CallTestTaskQue\u0027.",
      "revId": "9ab25b6c39958a6087bc27a7a613d194c0eca8a6",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "591b5c74_ce6e6b6e",
        "filename": "video/video_send_stream_tests.cc",
        "patchSetId": 2
      },
      "lineNbr": 1894,
      "author": {
        "id": 5508
      },
      "writtenOn": "2019-08-23T14:38:55Z",
      "side": 1,
      "message": "Have you tried this patch and found that to be the case? If so, can you share the stack traces? (including for when DestroyCalls is called)",
      "parentUuid": "cfcd879c_6c48870c",
      "revId": "9ab25b6c39958a6087bc27a7a613d194c0eca8a6",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "19185779_0e49d685",
        "filename": "video/video_send_stream_tests.cc",
        "patchSetId": 2
      },
      "lineNbr": 1956,
      "author": {
        "id": 5112
      },
      "writtenOn": "2019-08-23T14:55:53Z",
      "side": 1,
      "message": "nit: Should this be marked guarded by crit_?",
      "range": {
        "startLine": 1956,
        "startChar": 7,
        "endLine": 1956,
        "endChar": 31
      },
      "revId": "9ab25b6c39958a6087bc27a7a613d194c0eca8a6",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767",
      "unresolved": true
    }
  ]
}