{
  "comments": [
    {
      "key": {
        "uuid": "3dc78050_615947dc",
        "filename": "rtc_base/task_utils/repeating_task.cc",
        "patchSetId": 6
      },
      "lineNbr": 39,
      "author": {
        "id": 5126
      },
      "writtenOn": "2019-01-16T09:57:44Z",
      "side": 1,
      "message": "Hmm, did I just make you introduce a bug? It looks like you update next_run_time_ too early now, so that lost_time will be negative?",
      "revId": "a0186cb9b94e866dd9f9a4db85264e88e935c109",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "5f4a7664_972a070a",
        "filename": "rtc_base/task_utils/repeating_task.cc",
        "patchSetId": 6
      },
      "lineNbr": 39,
      "author": {
        "id": 5531
      },
      "writtenOn": "2019-01-16T11:01:26Z",
      "side": 1,
      "message": "Oh, indeed, my fault for missing test coverage for that. Added a test and fixed the code!",
      "parentUuid": "3dc78050_615947dc",
      "revId": "a0186cb9b94e866dd9f9a4db85264e88e935c109",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767",
      "unresolved": false
    }
  ]
}