{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "e736b34f_64831c1e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 5508
      },
      "writtenOn": "2024-04-16T15:32:32Z",
      "side": 1,
      "message": "Yes, that failure was due to this CL. I\u0027ve accounted for that case in the latest patch set. Can you take one more look?",
      "revId": "f61535cd7f4fc8c9259287cc9aea0f0ce5f3f461",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    }
  ]
}